version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      default:
        ipv4_address: 172.40.0.5
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'root-kafka-bitnami:latest'
    networks:
      default:
        ipv4_address: 172.40.0.6
    ports:
      - '9092:9092'
    volumes:
      - 'kafka:/var/lib/docker/volumes/kafka'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.6:9092
  

  kafka-rest:
    image: nodefluent/kafka-rest
    networks:
      default:
        ipv4_address: 172.40.0.7
    ports:
      - 8082:8082
    environment:
      # DEBUG: "*"
      KAFKA_REST_DEBUG: "all"
      KAFKA_REST_HTTP_PORT: 8082
      KAFKA_REST_CONSUMER_METADATA_BROKER_LIST: "172.40.0.6:9092"
      KAFKA_REST_PRODUCER_METADATA_BROKER_LIST: "172.40.0.6:9092"

  kafka-rest-ui:
    image: nodefluent/kafka-rest-ui
    networks:
      default:
        ipv4_address: 172.40.0.8
    ports:
      - 8000:8000
    environment:
      DEBUG: "*"
      REACT_APP_KAFKA_REST_URL: "http://172.40.0.7:8082/"
      REACT_APP_TIMEOUT: "3000"
      PROXY: "yes"
  

  # yahoo-manager:
  #   image: 'sheepkiller/kafka-manager'
  #   networks:
  #     default:
  #       ipv4_address: 172.40.0.7
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     - ZK_HOSTS='172.40.0.5:2181'
  #     - APPLICATION_SECRET=letmein

# docker run -it --rm  -p 9000:9000 -e ZK_HOSTS="your-zk.domain:2181" -e APPLICATION_SECRET=letmein sheepkiller/kafka-manager


  # kafka1:
  #   image: 'bitnami/kafka:2'
  #   networks:
  #     demo-net:
  #       ipv4_address: 172.40.0.7
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.7:9092
  # kafka2:
  #   image: 'bitnami/kafka:2'
  #   networks:
  #     demo-net:
  #       ipv4_address: 172.40.0.8
  #   environment:
  #     - KAFKA_BROKER_ID=3
  #     - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.8:9092

networks:
  default:
    external:
      name: kafka_python_api_demo-net


volumes:
  zookeeper_data:
    driver: local
  kafka:
    external: true