version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      demo-net:
        ipv4_address: 172.40.0.5
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:2'
    networks:
      demo-net:
        ipv4_address: 172.40.0.6
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.6:9092
  


  # kafka1:
  #   image: 'bitnami/kafka:2'
  #   networks:
  #     demo-net:
  #       ipv4_address: 172.40.0.7
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.7:9092
  # kafka2:
  #   image: 'bitnami/kafka:2'
  #   networks:
  #     demo-net:
  #       ipv4_address: 172.40.0.8
  #   environment:
  #     - KAFKA_BROKER_ID=3
  #     - KAFKA_ZOOKEEPER_CONNECT=172.40.0.5:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.40.0.8:9092


networks:
  demo-net:
    ipam:
      config:
        - subnet: 172.40.0.5/16



volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local