version: '3'

services:
  cassandra1:
    image: 'cassandra'

    volumes:
      - cassandra:/var/lib/docker/volumes/cassandra
          
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
  
  cassandra2:
    image: 'cassandra'
    volumes:
      - 'cassandra2_data:/var/lib/docker/volumes/cassandra'
    
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1


volumes:
  cassandra:
    external: true
  cassandra2_data:
    external: true
  


